# Generated by Django 4.2.13 on 2024-06-06 20:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.CharField(choices=[('piv', 'piv'), ('reparos_estruturais', 'reparos_estruturais'), ('vis_vidros', 'vis_vidros'), ('registro_km', 'registro_km'), ('grupo_extra', 'grupo_extra')], max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.CharField(choices=[('placa', 'placa'), ('traseira_esquerda', 'traseira_esquerda'), ('traseira_direita', 'traseira_direita'), ('frente_esquerda', 'frente_esquerda'), ('frente_direita', 'frente_direita'), ('grav_vidro_frontal', 'grav_vidro_frontal'), ('grav_vidro_dianteiro_esquerdo', 'grav_vidro_dianteiro_esquerdo'), ('grav_vidro_dianteiro_direito', 'grav_vidro_dianteiro_direito'), ('grav_vidro_traseiro_esquerdo', 'grav_vidro_traseiro_esquerdo'), ('grav_vidro_traseiro_direito', 'grav_vidro_traseiro_direito'), ('grav_vidro_traseiro', 'grav_vidro_traseiro'), ('painel_hodometro', 'painel_hodometro'), ('coluna_dianteira_esquerda', 'coluna_dianteira_esquerda'), ('coluna_central_esquerda', 'coluna_central_esquerda'), ('coluna_traseira_esquerda', 'coluna_traseira_esquerda'), ('coluna_traseira_direita', 'coluna_traseira_direita'), ('coluna_central_direita', 'coluna_central_direita'), ('compartimento_do_motor', 'compartimento_do_motor'), ('gravacao_motor', 'gravacao_motor'), ('gravacao_cambio', 'gravacao_cambio'), ('etiqueta_vis_comp_motor', 'etiqueta_vis_comp_motor'), ('etiqueta_vis_porta', 'etiqueta_vis_porta'), ('gravacao_chassi', 'gravacao_chassi'), ('longarina_dianteira_esquerda', 'longarina_dianteira_esquerda'), ('longarina_traseira_esquerda', 'longarina_traseira_esquerda'), ('longarina_traseira_direita', 'longarina_traseira_direita'), ('longarina_dianteira_direita', 'longarina_dianteira_direita'), ('documento', 'documento'), ('avarias_esteticas', 'avarias_esteticas'), ('avarias_estruturais', 'avarias_estruturais'), ('problemas_mecanicos', 'problemas_mecanicos'), ('problemas_eletricos', 'problemas_eletricos')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('inspection_groups', models.ManyToManyField(related_name='templates', to='inspection.inspectiongroup')),
            ],
        ),
    ]
