# Generated by Django 4.2.13 on 2024-06-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InspectionItems',
            new_name='InspectionItem',
        ),
    ]
