# Generated by Django 4.2.13 on 2024-06-06 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_rename_inspectionitems_inspectionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitem',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='inspection.inspectiongroup'),
        ),
    ]
