# Generated by Django 4.2.13 on 2024-06-07 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_inspectionitem_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification', models.CharField(choices=[('perfeito_estado', 'perfeito_estado'), ('danificada', 'danificada'), ('ausente', 'ausente'), ('possui_reparo', 'possui_reparo'), ('sem_reparo_aparente', 'sem_reparo_aparente'), ('possui_avaria', 'possui_avaria'), ('reparo_assoalho', 'reparo_assoalho'), ('reparo_porta_traseira', 'reparo_porta_traseira'), ('reparo_caixa_ar', 'reparo_caixa_ar'), ('reparo_caixa_rodas', 'reparo_caixa_rodas'), ('reparo_caixa_step', 'reparo_caixa_step'), ('reparo_lanterna', 'reparo_lanterna'), ('reparo_paralamas', 'reparo_paralamas'), ('reparo_parachoque', 'reparo_parachoque'), ('reparo_tampa_mala', 'reparo_tampa_mala'), ('reparo_teto', 'reparo_teto'), ('reparo_coluna_traseira', 'reparo_coluna_traseira'), ('reparo_painel_traseiro', 'reparo_painel_traseiro'), ('reparo_longarina', 'reparo_longarina'), ('original', 'original'), ('nao_original', 'nao_original'), ('inexistente', 'inexistente'), ('ilegivel', 'ilegivel'), ('divergente', 'divergente'), ('adulterada', 'adulterada'), ('apagado', 'apagado'), ('luz_airbag_acesa', 'luz_airbag_acesa'), ('luz_direcao_assistida', 'luz_direcao_assistida'), ('luz_freio_estacionamento', 'luz_freio_estacionamento'), ('luz_oleo_acesa', 'luz_oleo_acesa'), ('repetidor_seta_direita', 'repetidor_seta_direita'), ('repetidor_seta_esquerda', 'repetidor_seta_esquerda'), ('dentro_dos_padroes', 'dentro_dos_padroes'), ('fora_dos_padroes', 'fora_dos_padroes'), ('motor_ausente', 'motor_ausente'), ('motor_nao_liga', 'motor_nao_liga'), ('sem_bateria', 'sem_bateria'), ('com_vazamento', 'com_vazamento'), ('obstruida', 'obstruida'), ('remarcada', 'remarcada'), ('restaurada', 'restaurada'), ('lixada', 'lixada'), ('corroida', 'corroida'), ('inicio_oxidacao', 'inicio_oxidacao'), ('oxidada', 'oxidada'), ('obliterada', 'obliterada'), ('removida', 'removida'), ('incompleta', 'incompleta'), ('implatada', 'implatada'), ('paralela', 'paralela'), ('gravacao_regularizada_rem', 'gravacao_regularizada_rem'), ('falsificada', 'falsificada'), ('transplantada', 'transplantada'), ('nucleo_implatado', 'nucleo_implatado')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='vehicle',
            field=models.CharField(choices=[('carro', 'carro'), ('moto', 'moto')], default='carro', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InspectionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response', to='inspection.inspectionclassification')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response', to='inspection.inspectionitem')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('expiration', models.DateTimeField(default=datetime.datetime(2024, 6, 7, 18, 53, 35, 211077))),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection', to='inspection.inspectiontemplate')),
            ],
        ),
    ]
