# Generated by Django 4.2.13 on 2024-06-07 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_inspectionclassification_inspectiontemplate_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionitem',
            name='group',
        ),
        migrations.AddField(
            model_name='inspectiongroup',
            name='items',
            field=models.ManyToManyField(related_name='groups', to='inspection.inspectionitem'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 19, 2, 29, 403096)),
        ),
    ]
