# Generated by Django 4.2.13 on 2024-06-07 17:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_remove_inspectionitem_group_inspectiongroup_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectiongroup',
            name='items',
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='inspection.inspectiongroup'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 19, 5, 11, 457266)),
        ),
    ]
