# Generated by Django 4.2.13 on 2024-06-08 16:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_remove_inspectiongroup_items_inspectionitem_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionresponse',
            name='inspection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='inspection.inspection'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 8, 18, 57, 59, 128051)),
        ),
        migrations.AlterField(
            model_name='inspectionresponse',
            name='classification',
            field=models.CharField(choices=[('perfeito_estado', 'perfeito_estado'), ('danificada', 'danificada'), ('ausente', 'ausente'), ('possui_reparo', 'possui_reparo'), ('sem_reparo_aparente', 'sem_reparo_aparente'), ('possui_avaria', 'possui_avaria'), ('reparo_assoalho', 'reparo_assoalho'), ('reparo_porta_traseira', 'reparo_porta_traseira'), ('reparo_caixa_ar', 'reparo_caixa_ar'), ('reparo_caixa_rodas', 'reparo_caixa_rodas'), ('reparo_caixa_step', 'reparo_caixa_step'), ('reparo_lanterna', 'reparo_lanterna'), ('reparo_paralamas', 'reparo_paralamas'), ('reparo_parachoque', 'reparo_parachoque'), ('reparo_tampa_mala', 'reparo_tampa_mala'), ('reparo_teto', 'reparo_teto'), ('reparo_coluna_traseira', 'reparo_coluna_traseira'), ('reparo_painel_traseiro', 'reparo_painel_traseiro'), ('reparo_longarina', 'reparo_longarina'), ('original', 'original'), ('nao_original', 'nao_original'), ('inexistente', 'inexistente'), ('ilegivel', 'ilegivel'), ('divergente', 'divergente'), ('adulterada', 'adulterada'), ('apagado', 'apagado'), ('luz_airbag_acesa', 'luz_airbag_acesa'), ('luz_direcao_assistida', 'luz_direcao_assistida'), ('luz_freio_estacionamento', 'luz_freio_estacionamento'), ('luz_oleo_acesa', 'luz_oleo_acesa'), ('repetidor_seta_direita', 'repetidor_seta_direita'), ('repetidor_seta_esquerda', 'repetidor_seta_esquerda'), ('dentro_dos_padroes', 'dentro_dos_padroes'), ('fora_dos_padroes', 'fora_dos_padroes'), ('motor_ausente', 'motor_ausente'), ('motor_nao_liga', 'motor_nao_liga'), ('sem_bateria', 'sem_bateria'), ('com_vazamento', 'com_vazamento'), ('obstruida', 'obstruida'), ('remarcada', 'remarcada'), ('restaurada', 'restaurada'), ('lixada', 'lixada'), ('corroida', 'corroida'), ('inicio_oxidacao', 'inicio_oxidacao'), ('oxidada', 'oxidada'), ('obliterada', 'obliterada'), ('removida', 'removida'), ('incompleta', 'incompleta'), ('implatada', 'implatada'), ('paralela', 'paralela'), ('gravacao_regularizada_rem', 'gravacao_regularizada_rem'), ('falsificada', 'falsificada'), ('transplantada', 'transplantada'), ('nucleo_implatado', 'nucleo_implatado')], max_length=255),
        ),
        migrations.DeleteModel(
            name='InspectionClassification',
        ),
    ]
