# Generated by Django 4.2.13 on 2024-06-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_inspectionresponse_inspection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='expiration',
            field=models.DateTimeField(),
        ),
    ]
