# Generated by Django 4.2.13 on 2024-06-09 14:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_alter_inspection_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontemplate',
            name='groups_amount',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Maximo de grupos do template'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspectionitem',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='inspection.inspectiongroup', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='inspectionitem',
            name='item',
            field=models.CharField(choices=[('placa', 'placa'), ('traseira_esquerda', 'traseira_esquerda'), ('traseira_direita', 'traseira_direita'), ('frente_esquerda', 'frente_esquerda'), ('frente_direita', 'frente_direita'), ('grav_vidro_frontal', 'grav_vidro_frontal'), ('grav_vidro_dianteiro_esquerdo', 'grav_vidro_dianteiro_esquerdo'), ('grav_vidro_dianteiro_direito', 'grav_vidro_dianteiro_direito'), ('grav_vidro_traseiro_esquerdo', 'grav_vidro_traseiro_esquerdo'), ('grav_vidro_traseiro_direito', 'grav_vidro_traseiro_direito'), ('grav_vidro_traseiro', 'grav_vidro_traseiro'), ('painel_hodometro', 'painel_hodometro'), ('coluna_dianteira_esquerda', 'coluna_dianteira_esquerda'), ('coluna_central_esquerda', 'coluna_central_esquerda'), ('coluna_traseira_esquerda', 'coluna_traseira_esquerda'), ('coluna_traseira_direita', 'coluna_traseira_direita'), ('coluna_central_direita', 'coluna_central_direita'), ('compartimento_do_motor', 'compartimento_do_motor'), ('gravacao_motor', 'gravacao_motor'), ('gravacao_cambio', 'gravacao_cambio'), ('etiqueta_vis_comp_motor', 'etiqueta_vis_comp_motor'), ('etiqueta_vis_porta', 'etiqueta_vis_porta'), ('gravacao_chassi', 'gravacao_chassi'), ('longarina_dianteira_esquerda', 'longarina_dianteira_esquerda'), ('longarina_traseira_esquerda', 'longarina_traseira_esquerda'), ('longarina_traseira_direita', 'longarina_traseira_direita'), ('longarina_dianteira_direita', 'longarina_dianteira_direita'), ('documento', 'documento'), ('avarias_esteticas', 'avarias_esteticas'), ('avarias_estruturais', 'avarias_estruturais'), ('problemas_mecanicos', 'problemas_mecanicos'), ('problemas_eletricos', 'problemas_eletricos')], max_length=255, verbose_name='Item do grupo'),
        ),
        migrations.AlterField(
            model_name='inspectiontemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome do template'),
        ),
        migrations.AlterField(
            model_name='inspectiontemplate',
            name='vehicle',
            field=models.CharField(choices=[('carro', 'carro'), ('moto', 'moto')], max_length=255, verbose_name='Tipo de veículo'),
        ),
    ]
