# Generated by Django 4.2.13 on 2024-06-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0009_inspectiontemplate_groups_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionitem',
            name='group',
        ),
        migrations.AddField(
            model_name='inspectiongroup',
            name='items',
            field=models.ManyToManyField(related_name='group', to='inspection.inspectionitem'),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='name',
            field=models.CharField(default='teste', max_length=255),
            preserve_default=False,
        ),
    ]
