# Generated by Django 4.2.13 on 2024-06-13 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0011_remove_inspectiontemplate_groups_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='expiration',
        ),
        migrations.AddField(
            model_name='inspection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
