# Generated by Django 4.2 on 2024-06-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0012_remove_inspection_expiration_inspection_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionresponse',
            name='inspection',
        ),
        migrations.AddField(
            model_name='inspection',
            name='responses',
            field=models.ManyToManyField(null=True, related_name='inspection', to='inspection.inspectionresponse'),
        ),
    ]
